user-roles_index:
    path:     /
    defaults: { _controller: "AppBundle:UserRole:index" }
    methods:  GET

user-roles_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:UserRole:show" }
    methods:  GET

user-roles_new:
    path:     /new
    defaults: { _controller: "AppBundle:UserRole:new" }
    methods:  [GET, POST]

user-roles_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:UserRole:edit" }
    methods:  [GET, POST]

user-roles_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:UserRole:delete" }
    methods:  DELETE
