AppBundle\Entity\AppConfig:
    type: entity
    table: app_config
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pingRequestWaitingTime:
            type: integer
            nullable: true
            unsigned: false
            column: ping_request_waiting_time
    lifecycleCallbacks: {  }
