AppBundle\Entity\City:
    type: entity
    table: city
    indexes:
        city2state_idx:
            columns:
                - state_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 200
            fixed: false
    manyToOne:
        state:
            targetEntity: State
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_id:
                    referencedColumnName: state_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
