AppBundle\Entity\CodeStatus:
    type: entity
    table: code_status
    id:
        codeStatusId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_status_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 300
            fixed: false
            default: 'NULL'
        fromTable:
            type: string
            nullable: true
            length: 100
            fixed: false
            default: 'NULL'
            column: from_table
    lifecycleCallbacks: {  }
