AppBundle\Entity\InvoiceWhatsapp:
    type: entity
    table: invoice_whatsapp
    indexes:
        invoice_FK:
            columns:
                - staff_id
        invoice_whatsapp_FK:
            columns:
                - status
    id:
        invoiceId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: invoice_id
            generator:
                strategy: IDENTITY
    fields:
        imageName:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: image_name
        invoiceNumber:
            type: string
            nullable: true
            length: 100
            fixed: false
            default: 'NULL'
            column: invoice_number
        nit:
            type: string
            nullable: true
            length: 100
            fixed: false
            default: 'NULL'
        recurrent:
            type: integer
            nullable: false
            unsigned: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        productQuantity:
            type: integer
            nullable: true
            unsigned: false
            default: 'NULL'
            column: product_quantity
        totalInvoice:
            type: string
            nullable: true
            length: 100
            unsigned: false
            default: 'NULL'
            column: total_invoice
        prizeType:
            type: boolean
            nullable: true
            default: 'NULL'
            column: prize_type
        rejectionMessage:
            type: text
            nullable: true
            default: 'NULL'
            length: 300
            fixed: false
            column: rejection_message
        notifiStatus:
            type: string
            nullable: true
            default: 'NULL'
            length: 100
            fixed: false
            column: notifi_status
    manyToOne:
        staff:
            targetEntity: Staff
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                staff_id:
                    referencedColumnName: staff_id
            orphanRemoval: false
        status:
            targetEntity: MainStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                status:
                    referencedColumnName: main_status_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
