AppBundle\Entity\MessageStatus:
    type: entity
    table: message_status
    id:
        messageStatusId:
            type: integer
            nullable: false
            unsigned: false
            columnn: message_status_id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 60
            fixed: false
    lifecycleCallbacks: {  }
