AppBundle\Entity\MessageType:
    type: entity
    table: message_type
    id:
        messageTypeId:
            type: integer
            nullable: false
            unsigned: false
            columnn: message_type_id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 60
            fixed: false
    lifecycleCallbacks: {  }
