AppBundle\Entity\PromoJobPosition:
    type: entity
    table: promo_job_position
    repositoryClass: AppBundle\Repository\PromoJobPositionRepository
    indexes:
        promo_job_position_promo_id:
            columns:
                - promo_id
        promo_job_position_job_position_id:
            columns:
                - job_position_id
    id:
        promoJobPositionId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: promo_job_position_id
            generator:
                strategy: IDENTITY
    manyToOne:
        jobPosition:
            targetEntity: JobPosition
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_position_id:
                    referencedColumnName: id
            orphanRemoval: false
        promo:
            targetEntity: Promo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                promo_id:
                    referencedColumnName: promo_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
