AppBundle\Entity\PromoCc:
    type: entity
    table: promo_cc
    repositoryClass: AppBundle\Repository\PromoCcRepository
    indexes:
        promo_cc_promo_id:
            columns:
                - promo_id
    id:
        promoCcId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: promo_cc_id
            generator:
                strategy: IDENTITY
    fields:
        cc:
            type: string
            nullable: false
            length: 45
            fixed: false
    manyToOne:
        promo:
            targetEntity: Promo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                promo_id:
                    referencedColumnName: promo_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
