AppBundle\Entity\Region:
    type: entity
    table: region
    id:
        regionId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: region_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 200
            fixed: false
    lifecycleCallbacks: {  }
