AppBundle\Entity\StaffPromoPoints:
    type: entity
    table: staff_promo_points
    repositoryClass: AppBundle\Repository\StaffPromoPointsRepository
    indexes:
        fk_staff_id007_idx:
            columns:
                - staff_id
        fk_promo_id007_idx:
            columns:
                - promo_id
    id:
        staffPromoPointsId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: staff_promo_points_id
            generator:
                strategy: IDENTITY
    fields:
        points:
            type: float
            nullable: false
            precision: 11
            scale: 2
            default: '0.00'
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToOne:
        promo:
            targetEntity: Promo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                promo_id:
                    referencedColumnName: promo_id
            orphanRemoval: false
        staff:
            targetEntity: Staff
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                staff_id:
                    referencedColumnName: staff_id
            orphanRemoval: false
        sale:
            targetEntity: Sale
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sale_id:
                    referencedColumnName: sale_id
            orphanRemoval: false
        skuCategory:
            targetEntity: SkuCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sku_category_id:
                    referencedColumnName: sku_category_id
            orphanRemoval: false
        sku:
            targetEntity: Sku
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sku_id:
                    referencedColumnName: sku_id
            orphanRemoval: false               
    lifecycleCallbacks: {  }
