AppBundle\Entity\Status:
    type: entity
    table: status
    id:
        statusId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: status_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            fixed: false
            default: 'NULL'
        forTable:
            type: string
            nullable: true
            length: 100
            fixed: false
            default: 'NULL'
            column: for_table
        active:
            type: binary
            nullable: true
            default: 'NULL'
    lifecycleCallbacks: {  }
