AppBundle\Entity\Step:
    type: entity
    table: step
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        step:
            type: text
            nullable: false
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
