AppBundle\Entity\Store:
    type: entity
    table: store
    indexes:
        store2country_idx:
            columns:
                - country_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        storeName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: store_name
    manyToOne:
        country:
            targetEntity: Country
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
